Translated Descriptions
CheckIO-to-German/Cipher-Map pull request #3
Opened 2016-11-29 20:34 UTC by DahliaSR

Closes #2

2016-11-29 23:59 UTC, GiForce requested changes

2016-11-29 23:59 UTC, GiForce commented on translations/de/info/task_description.html
> +        sodass ich mir nicht diesen zufälligen Kauderwelsch merken muss.«, keiffte Sophia.<br>
Sofia (instead Sophia), but I recommend to end the speak without mentioning her again anyway. It's done before, it is clear Sofia is still speaking. Your choice of a verb isn't helping too :)

2016-11-29 23:59 UTC, GiForce commented on translations/de/info/task_description.html
> +    Außerdem lernst Du etwas die Fleißnersche Schablone, ein Verschlüsselungsverfahren aus
lieber
..lernst Du etwas über...
oder
...lernst Du wie die Fleißnersche Schablone funktioniert...
oder
..lernst Du etwas die Fleißnersche Schablone kennen...

2016-12-01 21:55 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Außerdem lernst Du etwas die Fleißnersche Schablone, ein Verschlüsselungsverfahren aus
:white_check_mark:

2016-12-01 21:58 UTC, DahliaSR commented on translations/de/info/task_description.html
> +        sodass ich mir nicht diesen zufälligen Kauderwelsch merken muss.«, keiffte Sophia.<br>
:white_check_mark:

2016-12-07 19:17 UTC, DahliaSR commented
@GiForce hier fehlt noch dein "Approval"

2016-12-07 19:45 UTC, GiForce approved these changes

2016-12-07 20:04 UTC, merged